NAME	=	at_least_this_beats_coffee_making

SRCS	=	main.cpp					\
			Bureaucrat.cpp				\
			AForm.cpp					\
			PresidentialPardonForm.cpp	\
			RobotomyRequestForm.cpp		\
			ShrubberyCreationForm.cpp	\
			Intern.cpp

INCS	=	Bureaucrat.hpp				\
			AForm.hpp					\
			PresidentialPardonForm.hpp	\
			RobotomyRequestForm.hpp		\
			ShrubberyCreationForm.hpp	\
			Intern.hpp

include ../template.mk
