NAME	=	no_you_need_form_28B_not_28C

SRCS	=	main.cpp					\
			Bureaucrat.cpp				\
			Form.cpp					\
			PresidentialPardonForm.cpp	\
			RobotomyRequestForm.cpp		\
			ShrubberyCreationForm.cpp

INCS	=	Bureaucrat.hpp				\
			Form.hpp					\
			PresidentialPardonForm.hpp	\
			RobotomyRequestForm.hpp		\
			ShrubberyCreationForm.hpp

include ../template.mk
